UserInfo:
  type: object
  properties:
    tenantId:
      type: string
      example: SJKOEWBIJHEFWWE8NS
    email:
      type: string
      example: test@zimesfield.com
    firstName:
      type: string
      example: admin
    lastName:
      type: string
      example: admin
    phone:
      type: string
      example: 2370123456789
    gender:
      $ref: "../schemas.yaml#/components/schemas/GenderEnum"
    authorities:
      type: array
      items:
        type: string
UserResponse:
  type: object
  properties:
    tenantId:
      type: string
      format: base64
    login:
      type: string
      example: omens
    firstName:
      type: string
      example: Omens
    lastName:
      type: string
      example: Odinaka
    email:
      type: string
      example: test@zimesfield.com
    imageUrl:
      type: string
      example: qazwsx
    phone:
      type: string
      example: 07012345678
    activated:
      type: string
      example: true
    createdBy:
      type: string
      example: omens
    createdAt:
      type: string
      example: "2021-09-07"
    lastModifiedBy:
      type: string
      example: omens
    lastModifiedAt:
      type: string
      example: "2021-09-07"
    address:
      $ref: '../schemas.yaml#/components/schemas/Address'
    dayOfBirth:
      type: string
      example: 5
    monthOfBirth:
      $ref: "../schemas.yaml#/components/schemas/MonthEnum"
    authorities:
      type: array
      items:
        type: string
    userStatus:
      $ref: "../schemas.yaml#/components/schemas/UserStatusEnum"

AdminRegistrationRequest:
    type: object
    required:
      - login
      - firstName
      - lastName
      - email
      - password
      - phone
      - address
    properties:
      uuid:
        type: string
        format: base64
      login:
        type: string
        example: omens
      firstName:
        type: string
        example: Omens
      lastName:
        type: string
        example: Odinaka
      email:
        type: string
      example: test@zimesfield.com
      imageUrl:
        type: string
        example: qazwsx
      phone:
        type: string
        example: 07012345678
      address:
        $ref: '../schemas.yaml#/components/schemas/Address'
      authorities:
        type: array
        items:
          type: string
      userStatus:
        $ref: '../schemas.yaml#/components/schemas/UserStatusEnum'

UserRegistrationRequest:
  type: object
  required:
    - firstName
    - lastName
    - email
    - phone
  properties:
    firstName:
      type: string
      example: Zimes
    lastName:
      type: string
      example: Field
    email:
      type: string
      example: test@zimesfield.com
    phone:
      type: string
      example: 07012345678
#    address:
#      $ref: '../schemas.yaml#/components/schemas/Address'
#    dayOfBirth:
#      type: string
#      example: 5
#    maritalStatus:
#      $ref: '../schemas.yaml#/components/schemas/MaritalStatusEnum'
#    gender:
#      $ref: '../schemas.yaml#/components/schemas/GenderEnum'
#    monthOfBirth:
#      $ref: "../schemas.yaml#/components/schemas/MonthEnum"

UserRegistrationResponse:
  type: object
  properties:
    tenantId:
      type: string
      example: "2b5901be-9f28-4fa4-b565-706cbbc699c5"
    login:
      type: string
      example: zimesfield
    firstName:
      type: string
      example: Zimes
    lastName:
      type: string
      example: Field
    email:
      type: string
      example: test@zimesfield.com

PasswordChangeRequest:
  type: object
  required:
    - currentPassword
    - newPassword
  properties:
    currentPassword:
      type: string
      example: test@123
    newPassword:
      type: string
      example: 123@test

KeyAndPasswordRequest:
  type: object
  required:
    - key
    - newPassword
  properties:
    key:
      type: string
      example: test@123
    newPassword:
      type: string
      example: 123@test


SignupRequest:
  type: object
  required:
    - tenantName
    - email
  properties:
    tenantName:
      type: string
      example: Zimesfield Limited
    email:
      type: string
      example: test@zimesfield.com

SignupResponse:
  type: object
  properties:
    tenantId:
      type: string
      example: "2b5901be-9f28-4fa4-b565-706cbbc699c5"
    tenantName:
      type: string
      example: Zimesfield Limited
    email:
      type: string
      example: test@zimesfield.com
    status:
      type: string
      example: PENDING

FinishSignupRequest:
  type: object
  required:
    - firstName
    - lastName
    - password
  properties:
    firstName:
      type: string
      example: Zimes
    lastName:
      type: string
      example: Field
    password:
      type: string
      example: test1234
