openapi: 3.0.3
info:
  title: Tenant Registration API
  version: 1.1.0
  description: API for registering tenants, validating input, verifying token, and sending notifications in a multi-tenant system.

servers:
  - url: '{protocol}://{environment}/{version}/api/{service}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      version:
        enum:
          - v1
        default: v1
      service:
        enum:
          - tenants
        default: tenants
      environment:
        default: localhost:8081    # Local server
        enum:
          - localhost:8081
          - api.profilenest.com         # Production server
          - dev.api.profilenest.com     # Development server
          - staging.api.profilenest.com # Staging server

tags:
  - name: Signup
    description: Tenant registration
  - name: Tenant
    description: Tenant management

security:
  - oauth: [ ]

paths:
  /signup:
    $ref: './paths/tenant/signup-init.yaml'

  /signup/verify:
    $ref: './paths/tenant/signup-verify.yaml'

  /signup/finish:
    $ref: './paths/tenant/signup-finish.yaml'

  /tenants:
    $ref: './paths/tenant/tenant-info.yaml'

  /tenants/email:
    $ref: './paths/tenant/update-email.yaml'

  /tenants/name:
    $ref: './paths/tenant/update-name.yaml'