openapi: 3.0.1
info:
  title: User API Contract
  description: 'This API contract defines the endpoints and operations for user management, authentication,
   and account operations in the Zimesfield platform.'
  termsOfService: 'https://swagger.io/terms/'
  contact:
    email: tech@zimesfield.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0

servers:
  - url: '{protocol}://{environment}/{version}/api/{service}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      version:
        enum:
          - v1
        default: v1
      service:
        enum:
          - users
        default: users
      environment:
        default: localhost:8081    # Local server
        enum:
          - localhost:8081
          - api.profilenest.com         # Production server
          - dev.api.profilenest.com     # Development server
          - staging.api.profilenest.com # Staging server

tags:
  - name: Register
    description: Registration for user
  - name: Authenticate
    description: Authenticate user
  - name: Account
    description: User account
  - name: Admin
    description: Operations about user

security:
  - oauth: [ user, email, profile ]
  - openId: [ user, email, profile ]

paths:
  /register:
    $ref: './paths/user/register.yaml'

  /authenticate:
    $ref: './paths/user/authenticate.yaml'
  /admin/users/{login}:
    $ref: './paths/user/managed-user.yaml'

  /api/admin/invite:
    $ref: './paths/user/invite-user.yaml'

  /activate:
    $ref: './paths/user/activate.yaml'

  /authenticated:
    $ref: './paths/user/is-authenticate.yaml'

  /auth:
    $ref: './paths/user/authenticate-info.yaml'

  /account:
    $ref: './paths/user/account.yaml'

  /account/change-password:
    $ref: './paths/user/change-password.yaml'

  /account/reset-password/init:
    $ref: './paths/user/reset-password-init.yaml'

  /account/reset-password/finish:
    $ref: './paths/user/reset-password-finished.yaml'

components:
  securitySchemes:
    oauth:
      type: oauth2
      description: OAuth2 with Keycloak
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:9080/realms/zimesfield/protocol/openid-connect/auth
          tokenUrl: http://localhost:9080/realms/zimesfield/protocol/openid-connect/token
          scopes:
            openid: Zimesfeld specific claims
            email: Email claims
            profile: Profile claims
    openId:
      type: openIdConnect
      openIdConnectUrl: http://localhost:9080/realms/jhipster/.well-known/openid-configuration
